CREATE TABLE banks (
    bank_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_name VARCHAR2(255) UNIQUE NOT NULL,
    package_name VARCHAR2(255)
);


-- Create table for reviews
CREATE TABLE reviews (
    review_id VARCHAR2(50) PRIMARY KEY,
    review CLOB,
    rating NUMBER(1),
    review_date DATE,
    bank_name VARCHAR2(100),
    source VARCHAR2(50)
);


select * from reviews